# Generated by Django 5.2.7 on 2025-11-05 00:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Número único do pedido de compra', max_length=50, unique=True)),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da compra')),
                ('data_entrega_prevista', models.DateField(blank=True, help_text='Data prevista para entrega', null=True)),
                ('data_entrega_realizada', models.DateField(blank=True, help_text='Data real da entrega', null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', help_text='Status atual da compra', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total da compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do frete', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto aplicado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a compra', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou a compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(help_text='Fornecedor da compra', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-data_compra'],
            },
        ),
    ]
