# Generated by Django on 2025-11-19
# Nome do arquivo: 0003_itemcompra.py
# Coloque na pasta: fornecedores/migrations/

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_compra'),  # Ajuste para a última migration existente
        ('produtos', '0001_initial'),  # Ajuste conforme necessário
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade do produto', validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário do produto no momento da compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal do item (quantidade × preço unitário)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(help_text='Compra à qual o item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fornecedores.compra')),
                ('produto', models.ForeignKey(help_text='Produto comprado', on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Itens de Compra',
                'db_table': 'itens_compra',
                'ordering': ['id'],
            },
        ),
    ]