# Generated by Django 5.2.6 on 2025-11-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('data_venda', models.DateTimeField()),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.CharField(max_length=255)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('itemVenda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.itemvenda')),
            ],
        ),
    ]
