# Generated by Django 5.2.7 on 2025-11-25 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField()),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('cliente_id', models.ForeignKey(blank=True, db_column='cliente_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'vendas_venda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('subTotal', models.DecimalField(db_column='subTotal', decimal_places=2, max_digits=10)),
                ('produto_id', models.ForeignKey(db_column='produto_id_id', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('venda_id', models.ForeignKey(db_column='venda_id_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'vendas_itemvenda',
                'managed': True,
            },
        ),
    ]
