# Generated by Django 5.2.7 on 2025-11-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='fake',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
