# Generated by Django 5.2.7 on 2025-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_fake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('nivel_acesso', models.PositiveBigIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=255)),
                ('cep', models.PositiveIntegerField()),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.PositiveBigIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('fake', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fake',
        ),
    ]
