# Generated by Django 5.2.7 on 2025-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionarios_remove_funcionario_fake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionarios',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nivel_acesso',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
