# Generated by Django 5.2.7 on 2025-11-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_delete_funcionarios_remove_funcionario_bairro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
